name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh
          sudo mv railway /usr/local/bin/railway

      - name: Build Docker Image
        run: docker build -t shavok .

      - name: Deploy to Railway.app
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --ci

